import { Download } from "lucide-react";
import { getTranslations } from "next-intl/server";
import { Button } from "@/components/ui/button";

type Props = {
  href: string;
};

/**
 * Server component — just renders a download link. The actual CSV is
 * generated by the route handler at `href` (under /api/export/...).
 */
export async function ExportButton({ href }: Props) {
  const t = await getTranslations("common");
  return (
    <Button asChild variant="outline" size="sm">
      <a href={href} download>
        <Download className="mr-2 h-3.5 w-3.5" />
        {t("exportCsv")}
      </a>
    </Button>
  );
}
