// AUTO-GENERATED by scripts/build-synergy-seed.mjs — DO NOT EDIT BY HAND.
// Re-run with:  node scripts/build-synergy-seed.mjs
//
// Source: ../../estrategia/synergy/guias/*.md
// Generated: 2026-07-13

export type SynergySeedActivity = {
  code: string;
  name: string;
  tagline: string | null;
  family: "wild" | "hive" | "multi";
  durationLabel: string | null;
  paxMin: number | null;
  paxMax: number | null;
  pricePerPaxMin: number | null;
  pricePerPaxMax: number | null;
  priceTargetMin: number | null;
  priceTargetMax: number | null;
  targetAudience: string | null;
  sortOrder: number;
  body: string;
};

export const SYNERGY_SEED: SynergySeedActivity[] = [
  {
    code: `hive-01-connect-circle`,
    name: `🗣 Connect Circle`,
    tagline: `Ex-*Words Connect*. Uma roda facilitada onde a equipa fala do que normalmente não fala. Um facilitador neutral segura o espaço. 90 minutos que mudam meses.`,
    family: "hive",
    durationLabel: `meio-dia (2-3h de círculo + intervalo)`,
    paxMin: 6,
    paxMax: 16,
    pricePerPaxMin: 30,
    pricePerPaxMax: 35,
    priceTargetMin: 30,
    priceTargetMax: 35,
    targetAudience: `equipas com tensão latente, novas equipas formadas, C-level, restart pós-crise`,
    sortOrder: 1,
    body: `# 🗣 Connect Circle
> Ex-*Words Connect*. Uma roda facilitada onde a equipa fala do que normalmente não fala. Um facilitador neutral segura o espaço. 90 minutos que mudam meses.

**Família:** 🏢 Hive
**Duração:** meio-dia (2-3h de círculo + intervalo)
**Participantes:** 6–16 (mais que isto perde intimidade)
**Local:** espaço fechado, cadeiras em círculo, sem mesa central (Leiria centro, sala de reuniões da empresa, quinta parceira)
**Estação:** todo o ano
**Público-alvo:** equipas com tensão latente, novas equipas formadas, C-level, restart pós-crise

## Objectivo pedagógico
Comunicação profunda, empatia, dissolução de resentimentos silenciosos, alinhamento emocional. **Óptimo depois de uma reestruturação ou fusão.**

## O que a equipa vive
Cadeiras em círculo. Não há mesa. Facilitador introduz "regras da roda": só fala quem tem o objecto (bússola de madeira Backpackers), sem interromper, sem julgar, sem responder imediatamente. Facilitador propõe 4-5 perguntas ao longo de 2h. As perguntas escalam gradualmente. No fim, cada pessoa diz UMA palavra sobre o que sente.

## Perguntas usadas (exemplo)

De leve para profundo:
1. "Que animal escolherias para ser durante 24h e porquê?"
2. "Uma coisa que aprendeste este ano — profissional ou pessoal — e que gostavas de partilhar"
3. "Qual foi o momento nesta equipa em que te sentiste mais orgulhoso?"
4. "Qual é a coisa que se tu não estivesses aqui, os outros iam perder?"
5. "Se a equipa fosse um clima, que clima seria hoje? E que clima gostavas que fosse daqui a 3 meses?"

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Objecto "palavra" (bússola madeira, pedra especial) | 1 | ✅ (símbolo Backpackers) |
| Cartões de reserva com perguntas | Set | ✅ |
| Timer discreto (facilitador) | 1 | ✅ |
| Bloco + caneta para cada pessoa (opcional) | 1 por pax | Consumível |
| Chá / água (não café — muda energia) | Suficiente | Consumível |

**Custo material** ≈ 30€. Actividade baratíssima a produzir.

## Fluxo

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Chegada + café | 15 min | Cria clima calmo | Chega |
| Contexto + regras | 15 min | Explica: sem julgar, ouvir, respirar | Aceita | 
| Ronda 1 (pergunta leve) | 30 min | Modera tempo por pessoa | Fala 2-3 min cada |
| Intervalo | 15 min | Bebe água | Descomprime |
| Rondas 2-4 (perguntas médias) | 60 min | Segura silêncios | Fala em profundidade |
| Ronda 5 (uma palavra final) | 15 min | Fecha simbolicamente | Sintetiza |
| Fecho + convívio | 20 min | Convida a levar aprendizado | Conversa livre |

## Facilitador — checklist
- [ ] **CRÍTICO:** ser neutral. Zero interpretação em tempo real, zero julgamento.
- [ ] Ter 8-10 perguntas de reserva por nível
- [ ] Ler a energia da sala — subir profundidade só se equipa está confortável
- [ ] Nunca deixar 2 pessoas conversarem entre si (é círculo, não diálogo)
- [ ] Segurar silêncios (aos 20 seg. começam a falar coisas verdadeiras)
- [ ] Ter almofadas ou tecido no meio (símbolo visual de espaço partilhado)
- [ ] Preparar espaço sem distracções (portátil desligado, telemóveis fora)

## Brief para o cliente
- **O que vive:** "Vão sentar-se em círculo durante 2h e conversar de forma diferente do habitual. Sem projector, sem PowerPoint, sem chat. O que sai daqui não se explica — vive-se."
- **O que traz:** disposição para ser genuíno, telemóvel fora, roupa confortável
- **O que levam:** insights internos + resumo escrito do facilitador (2 páginas, tema por tema, sem citação directa)

## Follow-up
- Resumo (2 páginas) do facilitador com **temas emergentes**, não citações
- **Nunca partilhar quem disse o quê.** A confidencialidade é 90% do valor.
- Convite opcional para 3 meses depois — nova ronda

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Alguém "toma o círculo" | Facilitador reintroduz regra do objecto |
| Silêncio embaraçoso | Facilitador segura 20 seg antes de intervir |
| Alguém chora | Facilitador acolhe, valida, respira, continua |
| Conflito aberto irrompe | Redirecionar para conversa 1-1 pós-círculo |
| Confidencialidade quebrada depois | Regras claras no início — nunca fora do círculo |

## Adaptações

- **Small team (6-8):** rondas mais longas, perguntas mais profundas
- **C-level (8-12):** foco em transição de liderança, decisões estratégicas
- **Equipa nova formada:** perguntas de identidade + expectativa
- **Pós-reestruturação:** enquadrar como "fecho de ciclo e abertura"
- **Digital / distribuído:** versão Zoom com regras estritas (câmara sempre on)

## Notas de custos
Preço-alvo: **~30-35€/pax**. Actividade baixo custo, alto impacto — óptima entrada comercial.
`,
  },
  {
    code: `hive-02-corporate-roleplay`,
    name: `🎬 Corporate Roleplay`,
    tagline: `A equipa vive cenas reais de trabalho — negociação difícil, dar feedback difícil, gerir conflito — em modo teatro estruturado. Aprendem fazendo, não ouvindo.`,
    family: "hive",
    durationLabel: `meio-dia a dia inteiro (3-6h)`,
    paxMin: 8,
    paxMax: 20,
    pricePerPaxMin: 35,
    pricePerPaxMax: 40,
    priceTargetMin: 35,
    priceTargetMax: 40,
    targetAudience: `equipas comerciais, vendas, gestão de conflito, gestão de projecto, RH`,
    sortOrder: 2,
    body: `# 🎬 Corporate Roleplay
> A equipa vive cenas reais de trabalho — negociação difícil, dar feedback difícil, gerir conflito — em modo teatro estruturado. Aprendem fazendo, não ouvindo.

**Família:** 🏢 Hive
**Duração:** meio-dia a dia inteiro (3-6h)
**Participantes:** 8–20
**Local:** sala espaçosa com espaço para "cena" + audiência
**Estação:** todo o ano
**Público-alvo:** equipas comerciais, vendas, gestão de conflito, gestão de projecto, RH

## Objectivo pedagógico
Resolução de conflitos, feedback assertivo, negociação, escuta activa. **Aprender-fazendo em vez de aprender-ouvindo.** É a antítese da formação corporate tradicional.

## O que a equipa vive
Facilitador apresenta 4-6 cenas: cliente insatisfeito, feedback negativo a colaborador, negociação com fornecedor, reunião com sócio disruptivo, etc. Dois voluntários por cena — outros são "audiência engaged" (comentam pós-cena). Após cada cena, dinâmica de re-play: "e se fosse assim?".

## Cenas típicas (banco)

- **Cliente insatisfeito** — cliente exige reembolso injusto; comercial tem de recusar sem perder relação
- **Feedback difícil** — dizer a um colaborador de longa data que a performance caiu
- **Negociação de preço** — cliente quer 30% desconto; vendedor tem margem 10%
- **Conflito entre pares** — dois gestores discutem prioridades de departamento
- **Onboarding chato** — novo colaborador sente-se ignorado, precisa dizer algo
- **Salto salarial** — colaborador pede aumento; gestor não tem orçamento

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Cartões cena (descrição + personagens) | Set 8-10 | ✅ |
| Objectos cenográficos (mesa, telefone, cadeiras) | Set | ✅ |
| Câmara para gravar cenas (opcional) | 1 | ✅ |
| Timer visível | 1 | ✅ |
| Bloco + caneta por pax (para notas de audiência) | 1 por pax | Consumível |

**Custo material** ≈ 50€.

## Fluxo (versão meio-dia, 3h)

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Contexto + regras | 20 min | Explica: cena → replay → discussão | Escuta |
| Cena 1 (facilitador demonstra) | 20 min | Demonstra com 1 voluntário | Observa como se fizesse |
| Cenas 2-4 (equipa executa) | 90 min | Modera, fornece feedback | Interpreta |
| Discussão colectiva | 30 min | Facilita: "o que aprendemos?" | Reflecte |
| Cena 5 (super-cena final) | 30 min | Cena complexa com 4-5 pessoas | Executa |
| Fecho + fotos | 20 min | Convida a levar 1 skill | Sintetiza |

## Facilitador — checklist
- [ ] Ter 10+ cenas de banco, escolher 4-5 alinhadas com o problema real do cliente
- [ ] Nunca forçar ninguém a fazer cena — voluntariado
- [ ] Facilitar bem o replay: "e se a Ana tivesse dito X em vez de Y?"
- [ ] Nunca ridicularizar quem faz cena — celebrar coragem
- [ ] Time-boxing rigoroso (senão vira teatro)
- [ ] Ter 2-3 cenas "hardcore" opcionais para C-level

## Brief para o cliente
- **O que vive:** "Vão fazer teatro estruturado sobre cenas reais do vosso trabalho. Vão ver, em directo, alternativas à forma como normalmente reagem. Vão sair com skills, não com slides."
- **O que traz:** disposição para se expor, roupa smart casual, sentido de humor
- **O que levam:** vídeos das cenas (se autorização), grelha de skills observados, plano de acção 30 dias

## Follow-up
- **Grelha comportamental** — quem mostrou skill de escuta, feedback, negociação. Óptimo para o RH mapear talentos.
- Vídeo curto (opcional) para reuso interno
- Convite para 3 meses depois: "vamos rever as cenas em pequeno grupo?"

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Alguém recusa fazer cena | OK — é audiência engaged |
| Cena vira desconforto real (conflito activo) | Facilitador corta, redireciona para 1-1 privado |
| Cena vira paródia (sem seriedade) | Facilitador puxa energia com cena mais complexa |
| Alguém expõe caso real (delicado) | Facilitador enquadra "só ficção, sem reais" |

## Adaptações

- **Small team (8-10):** todos participam, mais rondas por pessoa
- **Grande grupo (20+):** dividir em 3 sub-grupos com cenas paralelas
- **Vendas/comercial:** só cenas de negociação
- **Gestão média:** só cenas de feedback + gestão de equipa
- **C-level:** cenas de comunicação executiva + gestão de stakeholders

## Notas de custos
Preço-alvo: **~35-40€/pax**. Ver \`custos.md\`.
`,
  },
  {
    code: `hive-03-canvas-of-ideas`,
    name: `🎨 Canvas of Ideas`,
    tagline: `Fundido com *Brainstorm Arena*. Workshop de ideação estruturada. A equipa produz 50+ ideias, filtra, prioriza, sai com um plano concreto.`,
    family: "hive",
    durationLabel: `meio-dia a dia inteiro (3-6h)`,
    paxMin: 8,
    paxMax: 30,
    pricePerPaxMin: 40,
    pricePerPaxMax: 45,
    priceTargetMin: 40,
    priceTargetMax: 45,
    targetAudience: `marketing, produto, inovação, gestão que precisa de novas ideias mensuráveis`,
    sortOrder: 3,
    body: `# 🎨 Canvas of Ideas
> Fundido com *Brainstorm Arena*. Workshop de ideação estruturada. A equipa produz 50+ ideias, filtra, prioriza, sai com um plano concreto.

**Família:** 🏢 Hive
**Duração:** meio-dia a dia inteiro (3-6h)
**Participantes:** 8–30 (mesas de 4-6)
**Local:** sala ampla com mesas separadas, muitas paredes brancas ou flipcharts
**Estação:** todo o ano
**Público-alvo:** marketing, produto, inovação, gestão que precisa de novas ideias mensuráveis

## Objectivo pedagógico
Ideação estruturada (quantidade → qualidade), filtragem colectiva, alinhamento em prioridades. Anti-brainstorm "para dizer que se fez brainstorm" — este entrega saída acionável.

## O que a equipa vive
Facilitador lança 1 pergunta central (ex: "Como duplicamos a retenção em 12 meses?" ou "Que produto lançamos em 2027?"). Sessão em 4 fases:
1. **Divergir** (silêncio + post-its) — 40 min, 100+ ideias
2. **Convergir** (afinidade + votação) — 45 min, top 10
3. **Aprofundar** (canvas por ideia) — 60 min, top 3
4. **Priorizar + comprometer** (matriz esforço/impacto + owners) — 45 min

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Post-its (várias cores) | 500+ | Consumível |
| Marcadores permanentes | 1 por pax | Consumível parcial |
| Flipcharts / paredes brancas grandes | 4-6 | ✅ |
| Cronómetro visível | 1 | ✅ |
| Canvas printado (framework de aprofundamento) | 1 por top-3 | Consumível |
| Dot-stickers para votação | 500 | Consumível |
| Templates estruturados (Impact/Effort matrix) | 1 grande | ✅ |

**Custo material** ≈ 90€. Investimento em templates plastificados reutilizáveis: ~200€ amortizado em 5 eventos.

## Fluxo (versão dia inteiro, 6h com almoço)

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Chegada + energizer | 20 min | Icebreaker rápido | Aquece |
| Pergunta central + regras | 30 min | Enquadra o problema | Alinha |
| Divergir (silêncio) | 40 min | Cronometra | Escreve post-its em silêncio |
| Divergir (verbal, "sim, e...") | 30 min | Facilita, não julga | Constrói em cima |
| Almoço | 60 min | Convive | Descomprime |
| Convergir (afinidade) | 30 min | Ensina agrupamento | Agrupa temas |
| Votação | 15 min | Explica critérios | Cola dots |
| Aprofundar top-3 (canvas) | 90 min | Modera mesas | Trabalha em profundidade |
| Priorizar (matriz) | 30 min | Facilita decisão | Aloca esforço/impacto |
| Comprometer (owners + prazos) | 30 min | Cronómetro final | Assume tarefas |
| Fecho | 15 min | Sintetiza | Regista |

## Facilitador — checklist
- [ ] Pergunta central bem formulada (não muito ampla, não estreita) — trabalhar com cliente 1 semana antes
- [ ] Templates canvas prontos e testados
- [ ] Regras claras (não julgar, quantidade > qualidade em divergência, silenciar telemóveis)
- [ ] Iluminação boa (energia da sala depende)
- [ ] Ritmo firme — não deixar arrastar
- [ ] Cameraman para capturar paredes cheias de post-its (foto entregável)
- [ ] Facilitador NÃO opina em ideias

## Brief para o cliente
- **O que vive:** "Vão sair com um roteiro de 3 acções concretas e responsáveis. Não é workshop 'a acabar em nada'. A pergunta central é vossa — a saída é vossa. Nós somos a estrutura."
- **O que traz:** disposição para gerar sem editar, roupa confortável
- **O que levam:** relatório com 100+ ideias documentadas + roteiro com top-3 + owners + prazos + fotos das paredes

## Follow-up
- **Relatório completo** — 100+ ideias tabuladas, agrupadas, votadas
- Roteiro top-3 com canvas preenchido
- Fotos alta resolução das paredes de trabalho
- Follow-up call 30 dias depois: "estão a executar? O que travou?"

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Pergunta central mal formulada | Trabalhar com cliente 1 sem antes (obrigatório) |
| Equipa fica em "brainstorm eterno" | Cronómetro rigoroso |
| Alguém domina divergência | Regra do silêncio na fase 1 |
| Falta de commitment no fim | Escrever owner + prazo na parede visível |

## Adaptações

- **Small team (8):** menos ideias por pessoa, mais aprofundamento
- **Grande grupo (30):** 5 mesas paralelas, retorno colectivo
- **Foco produto:** aprofundamento com Value Proposition Canvas
- **Foco processo:** aprofundamento com SIPOC ou Lean Canvas
- **Distribuído:** versão Miro + Zoom (perde 30% de energia mas funciona)

## Notas de custos
Preço-alvo: **~40-45€/pax**. Ver \`custos.md\`.
`,
  },
  {
    code: `hive-04-personality-code-disc`,
    name: `🔍 The Personality Code — DISC/FLEX`,
    tagline: `⭐ **Âncora premium do catálogo Hive.** Perfil comportamental oficial DISC/FLEX + workshop de aplicação em equipa. Ticket alto, entregável físico (relatórios).`,
    family: "hive",
    durationLabel: `dia inteiro (6h + 1h por relatório individual)`,
    paxMin: 6,
    paxMax: 20,
    pricePerPaxMin: 70,
    pricePerPaxMax: 90,
    priceTargetMin: 70,
    priceTargetMax: 90,
    targetAudience: `C-level, equipas de gestão, novos comités, empresas em fase de contratação intensa`,
    sortOrder: 4,
    body: `# 🔍 The Personality Code — DISC/FLEX
> ⭐ **Âncora premium do catálogo Hive.** Perfil comportamental oficial DISC/FLEX + workshop de aplicação em equipa. Ticket alto, entregável físico (relatórios).

**Família:** 🏢 Hive
**Duração:** dia inteiro (6h + 1h por relatório individual)
**Participantes:** 6–20 (mais que 20 perde qualidade individual)
**Local:** sala com internet fiável (para questionário online)
**Estação:** todo o ano
**Público-alvo:** C-level, equipas de gestão, novos comités, empresas em fase de contratação intensa

## ⚠️ Pré-requisito de credibilidade

**Certificação DISC oficial** (ou FLEX ou outro instrumento reconhecido). Sem certificação:
- Não vender esta actividade (compromete a marca)
- **Alternativa:** partnership com facilitador certificado externo (revenue-share)

Custo certificação: ~800-1500€, 5-7 dias de formação. Fazer 1x, amortiza em 10 vendas.

## Objectivo pedagógico
Autoconhecimento comportamental + adaptação de estilos + comunicação entre perfis diferentes. Entregável = relatório individual (10-15 páginas) que a pessoa leva para a vida.

## O que a equipa vive

1. **Pré-evento:** cada pessoa faz questionário online (25 min) 1 semana antes
2. **Dia do evento:**
   - Manhã: descoberta do próprio perfil + partilha em roda
   - Almoço: partilha informal
   - Tarde: dinâmicas de aplicação (comunicação cruzada, feedback ajustado ao estilo, prevenção de conflito)
3. **Pós-evento:** relatório individual + plano de aplicação 30 dias

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Licenças DISC (uma por pax) | Por pax | Consumível (~15-25€/lic) |
| Relatórios impressos personalizados | 1 por pax | Consumível |
| Roda de perfis grande (parede) | 1 | ✅ |
| Cartões cor por perfil (D/I/S/C) | Set | ✅ |
| Templates de dinâmicas | Set | ✅ |
| Bloco personalizado para notas | 1 por pax | Consumível |

**Custo material total** ≈ 150€ + relatórios (variável). Facilitador certificado obrigatório.

## Fluxo (dia inteiro)

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Chegada + café | 20 min | Recebe | Chega |
| Contexto DISC (o modelo) | 45 min | Ensina o modelo | Aprende |
| Reveal individual perfis | 45 min | Cada pessoa recebe o seu | Descobre |
| Ronda partilha | 60 min | Facilita: "isto surpreende-te?" | Partilha |
| Almoço | 60 min | Convive | Descomprime |
| Dinâmica 1: comunicar cruzado | 45 min | Cenas por perfil oposto | Executa |
| Dinâmica 2: gerir conflito | 45 min | Simulação | Executa |
| Aplicação na equipa | 45 min | "Mapa da equipa" na parede | Colabora |
| Plano de 30 dias | 30 min | Cada um define compromisso | Compromete-se |
| Fecho | 15 min | Sintetiza | Regista |

## Facilitador — checklist
- [ ] Certificado DISC ou FLEX válido (**impossível fazer sem**)
- [ ] Enviar questionário 7 dias antes
- [ ] Analisar resultados 2 dias antes (para preparar dinâmicas de aplicação)
- [ ] Preparar relatórios impressos personalizados
- [ ] Ter roda de perfis visível
- [ ] Nunca julgar um perfil (só diferentes, nunca "melhor")
- [ ] Preparar 3-4 exemplos reais para cada perfil

## Brief para o cliente
- **O que vive:** "Vão descobrir o vosso perfil comportamental por baseado em ciência (30 anos de investigação). Vão sair com uma linguagem comum para falar sobre estilos. Vão saber por que aquela pessoa vos irrita — e como comunicar melhor com ela."
- **O que traz:** honestidade no questionário, disposição para autoanálise
- **O que levam:** relatório individual (10-15 pág), mapa da equipa, plano de 30 dias

## Follow-up
- Relatório individual encadernado (via email + versão física opcional)
- **Mapa da equipa** — infográfico com todos os perfis, dinâmicas de comunicação recomendadas
- Sessão follow-up 60 dias (opcional, ~40% clientes contratam) — revisita perfis, ajusta plano
- Convite para "shadowing" — 1 mês depois, observar 1 reunião real da equipa e dar feedback

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Alguém "não gosta do seu perfil" | Enquadramento: perfis são pontos de vista, não sentenças |
| Perfil usado para julgar / rotular | Regra clara: perfil é lente, não etiqueta |
| Cliente quer "medir se A é melhor gestor que B" | Recusar — DISC não mede performance |
| Ronda torna-se demasiado íntima | Facilitador ajusta profundidade |

## Adaptações

- **Small team (6-10):** rondas mais profundas, mais dinâmicas em duplas
- **C-level (8-12):** enfoque em delegação, comunicação estratégica, feedback executivo
- **Após reestruturação:** enfoque em mapear a nova equipa
- **Comercial:** enfoque em adaptar estilo ao cliente
- **Distribuído:** possível 100% online (Zoom + Miro + relatórios digitais)

## Notas de custos
Preço-alvo: **~70-90€/pax**. Ticket alto justificado pelo entregável físico (relatórios) e certificação.
**Muito superior à maioria das actividades — vender para C-level e gestão média, não para toda a empresa.**
`,
  },
  {
    code: `hive-05-big-pub-quiz`,
    name: `🧠 Big Pub Quiz`,
    tagline: `Um quiz colectivo, temático, animado. Zero preparação. Ambiente relaxado. Ganha a equipa que sabe mais + colabora mais rápido.`,
    family: "hive",
    durationLabel: `2-3h (à noite ou após reunião)`,
    paxMin: 10,
    paxMax: 50,
    pricePerPaxMin: 30,
    pricePerPaxMax: 35,
    priceTargetMin: 30,
    priceTargetMax: 35,
    targetAudience: `qualquer equipa, muito bom para fecho de ano, aniversários, kickoffs`,
    sortOrder: 5,
    body: `# 🧠 Big Pub Quiz
> Um quiz colectivo, temático, animado. Zero preparação. Ambiente relaxado. Ganha a equipa que sabe mais + colabora mais rápido.

**Família:** 🏢 Hive
**Duração:** 2-3h (à noite ou após reunião)
**Participantes:** 10–50 (equipas de 4-6)
**Local:** sala grande, restaurante, quinta de eventos, escritório com pizza
**Estação:** todo o ano
**Público-alvo:** qualquer equipa, muito bom para fecho de ano, aniversários, kickoffs

## Objectivo pedagógico
Colaboração leve, celebração, descompressão. **É o entretenimento inteligente do catálogo.** Baixa exigência emocional, alta energia.

## O que a equipa vive
6-8 rondas de 10 perguntas. Temas: cultura geral, empresa (histórico da empresa + curiosidades), história de Portugal, música anos 90-2000, cinema, cultura pop, "adivinha o colega" (fotos de infância), etc. Facilitador é MC. Prémios simbólicos por ronda. Grande prémio final.

## Rondas típicas

1. **Warm-up geral** (cultura geral leve)
2. **Sobre a empresa** — perguntas personalizadas (preparadas com o cliente 1 semana antes)
3. **Adivinha o colega** — foto de infância → adivinhar quem é
4. **Música** — reconhecer canções (áudio)
5. **Imagem** — adivinhar filme/série pela imagem
6. **Rapid fire** — perguntas rápidas, 10 seg por resposta
7. **Ronda final "hard"** — perguntas difíceis, mais pontos
8. **Bónus (opcional)** — desafio físico rápido

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Projector + tela + som | 1 set | ✅ (aluguer se n/a) |
| Slides preparados (rondas) | Set | ✅ (adaptar por cliente) |
| Cartões resposta impressos | 1 set por equipa por ronda | Consumível |
| Buzzers ou sinos por equipa (opcional) | 4-8 | ✅ |
| Prémios simbólicos por ronda | 6-8 | Consumível |
| Grande prémio final | 1 | Consumível |
| Microfone | 1 | ✅ |

**Custo material** ≈ 40€.

## Fluxo

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Boas-vindas + regras | 10 min | Anima como MC | Diverte-se |
| Formação equipas + nomes | 10 min | Facilita | Escolhe nome, cria team |
| Ronda 1 | 15 min | Apresenta perguntas | Responde |
| Ronda 2 (empresa) | 15 min | Enquadra | Responde + comenta |
| Rondas 3-4 (foto colegas, música) | 30 min | Anima | Ri e responde |
| Ronda 5-6 (imagem, rapid fire) | 25 min | Cronómetro | Responde rápido |
| Ronda 7 (hard) | 20 min | Sério | Concentra |
| Cerimónia final | 15 min | Anuncia vencedores | Celebra |

## Facilitador — checklist
- [ ] Slides preparados (2 sem antes) com perguntas específicas da empresa
- [ ] Testar projector + som antes
- [ ] Ter prémios simbólicos por ronda
- [ ] Buzzers ou sinos preparados
- [ ] Preparar 5-10 perguntas de reserva para desempate
- [ ] Cronómetro visível
- [ ] Ser bom MC — energia alta, humor, ritmo

## Brief para o cliente
- **O que vive:** "Vão passar 2 horas em ambiente relaxado a jogar em equipa. Vão descobrir quem sabe muito de cultura pop e quem sabe mesmo detalhes da história da empresa. É o formato ideal para fim de ano, kickoff, ou aniversário da empresa."
- **O que traz:** disposição para brincar, competitividade sã
- **O que levam:** fotos + vídeo curto + certificado equipa vencedora

## Follow-up
- Fotos + vídeo montado
- Slide "equipa vencedora" para o mural do escritório
- Slides do quiz partilhados para reuso interno futuro

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Uma equipa vai claramente à frente | Rondas em que o vencedor troca (rapid fire, imagem) |
| Perguntas muito difíceis | Ronda 7 tem "hard" mas as outras são acessíveis |
| Alguém não sabe nada | Nome da equipa + rondas colaborativas nivelam |
| Cliente quer perguntas específicas mas não fornece dados | Trabalhar 2 sem antes com pedido de "20 factos únicos da empresa" |

## Adaptações

- **Small team (10-15):** 2-3 equipas, rondas mais longas
- **Grande grupo (50):** 8-10 equipas, cerimónia final estruturada
- **Fim de ano:** ronda temática sobre o ano da empresa
- **Kickoff Janeiro:** ronda "adivinha objectivos" (revela objectivos anuais no formato de perguntas)
- **Distribuído:** versão Kahoot online — funciona, perde ambiente físico
- **Combinar com jantar:** ronda entre pratos + prémio no dessert

## Notas de custos
Preço-alvo: **~30-35€/pax**. Actividade mais leve — óptima para fecho de projecto, aniversário, fim de ano.
`,
  },
  {
    code: `hive-06-backpackers-beat`,
    name: `🥁 Backpackers Beat`,
    tagline: `**Novidade 2026.** Drum circle facilitado — 60-90 minutos de percussão colectiva em círculo. Sem experiência musical. Sem palavras. Só ritmo e escuta.`,
    family: "hive",
    durationLabel: `90 minutos a 2h (activo) + convívio`,
    paxMin: 15,
    paxMax: 60,
    pricePerPaxMin: 65,
    pricePerPaxMax: 80,
    priceTargetMin: 65,
    priceTargetMax: 80,
    targetAudience: `empresas em fase de "reconstruir cultura", pós-fusão, saúde/wellbeing corporativo, celebrações`,
    sortOrder: 6,
    body: `# 🥁 Backpackers Beat
> **Novidade 2026.** Drum circle facilitado — 60-90 minutos de percussão colectiva em círculo. Sem experiência musical. Sem palavras. Só ritmo e escuta.

**Família:** 🏢 Hive (com adaptação outdoor)
**Duração:** 90 minutos a 2h (activo) + convívio
**Participantes:** 15–60 (limite = número de instrumentos)
**Local:** sala grande com boa acústica ou espaço outdoor coberto
**Estação:** todo o ano
**Público-alvo:** empresas em fase de "reconstruir cultura", pós-fusão, saúde/wellbeing corporativo, celebrações

**Novidade — não estava no catálogo original.** Referência PT: Emotion e Cegoc oferecem versões. Diferenciação: Backpackers usa instrumentos artesanais + facilitador com formação musical + storytelling da Amazónia/África de onde vêm os ritmos.

## Objectivo pedagógico
Escuta activa não-verbal, sincronização de grupo, wellbeing (libertação de endorfinas), quebra de barreiras hierárquicas (todos são iguais no círculo).

## O que a equipa vive
Facilitador (com formação em percussão) apresenta uma tribo/ritmo (ex: djembes africanos, ritmo brasileiro). Cada pessoa recebe um instrumento. Facilitador ensina 3-4 ritmos base. A equipa toca em conjunto, camadas em cima de camadas. No fim, "jam session" livre. Momento profundo, quase espiritual.

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Djembes / tambores mão | 1 por pax | ✅ (aluguer ~10€/dia/instr) |
| Percussão auxiliar (maracas, tamborins, agogôs) | Extras | ✅ |
| Facilitador com formação | 1 | Externo — precisa parceria |
| Colunas + microfone | Set | ✅ |
| Almofadas/cadeiras sem braços | 1 por pax | ✅ |

**Custo material** ≈ 250€ (aluguer instrumentos para 20 pax). **Precisa parceria com percussionista certificado** (60-100€/hora facilitador).

## Fluxo

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Chegada + café | 10 min | Recebe | Chega |
| Contexto + demo instrumento | 20 min | Toca demo + storytelling | Ouve |
| Ritmo 1 (mão dominante) | 15 min | Ensina batida simples | Toca junto |
| Ritmo 2 (mão auxiliar) | 15 min | Adiciona camada | Sobrepõe |
| Improvisação livre | 20 min | Guia crescendo/decrescendo | Toca com autonomia |
| Silêncio + reflexão | 10 min | Facilita momento | Sente |
| Fecho + convívio | 20 min | Convida a partilhar sensação | Conversa livre |

## Facilitador — checklist
- [ ] Parceria com percussionista profissional (~60-100€/h)
- [ ] Alugar/comprar 30-40 instrumentos base
- [ ] Storytelling preparado sobre origem cultural do ritmo
- [ ] Espaço com boa acústica (sem eco excessivo)
- [ ] Testar volume — não incomodar vizinhos
- [ ] Convidar mais silêncios que ritmos (o valor está no contraste)
- [ ] Vídeo profissional do momento cresce (entregável poderoso)

## Brief para o cliente
- **O que vive:** "Vão passar 90 minutos a tocar juntos, sem falar. Não precisam saber música. Vão descobrir que a vossa equipa consegue sincronizar-se de uma forma que uma reunião nunca permite. É difícil descrever — vive-se."
- **O que traz:** roupa confortável, disposição para deixar o "profissional" à porta
- **O que levam:** vídeo profissional 90-s do jam session, memória sensorial partilhada (super duradoura)

## Follow-up
- Vídeo profissional 90-s
- Foto de grupo com instrumentos
- Áudio raw do jam final (para partilhar interno)
- Convite para 2ª sessão semestral (~40% clientes voltam)

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Alguém "não gosta de tambor" | Pode ficar em percussão auxiliar (maracas, agogôs) |
| Volume incomoda vizinhos | Verificar local + horários |
| Facilitador com pouca experiência | Só trabalhar com parceiros certificados |
| Equipa fica embaraçada | Facilitador cria warm-up bom |

## Adaptações

- **Small team (15):** todos com djembe, mais aprofundamento em cada ritmo
- **Grande grupo (60):** camadas complexas com mais percussão, mais teatral
- **Outdoor:** hoguera ao pôr-do-sol + percussão (foto absurdamente boa)
- **Wellbeing corporativo:** combinar com yoga/mindfulness antes/depois
- **Fecho de ano:** combinar com jantar em quinta

## Notas de custos
Preço-alvo: **~65-80€/pax**. Ticket alto justificado por: instrumentos, facilitador especializado, entregável vídeo profissional. **Vender como experiência premium.**

## Parcerias-alvo

- **Percussionista profissional:** Ricardo Nascimento (Leiria), Grupo Ciranda (Lisboa), África em Portugal (Coimbra)
- **Quinta com espaço:** parceria com quintas de eventos Fórnea/Alcobaça
`,
  },
  {
    code: `hive-07-backpackers-studio`,
    name: `🎬 Backpackers Studio`,
    tagline: `**Novidade 2026.** Em meio dia, cada equipa concebe, filma e edita um curta de 60-90 seg. Cerimónia final tipo Oscars. Vídeos ficam com a empresa.`,
    family: "hive",
    durationLabel: `dia inteiro (5-6h) ou meio-dia intensivo (4h)`,
    paxMin: 12,
    paxMax: 36,
    pricePerPaxMin: 55,
    pricePerPaxMax: 70,
    priceTargetMin: 55,
    priceTargetMax: 70,
    targetAudience: `marketing, criativos, tech, retalho — qualquer equipa que valorize output partilhável`,
    sortOrder: 7,
    body: `# 🎬 Backpackers Studio
> **Novidade 2026.** Em meio dia, cada equipa concebe, filma e edita um curta de 60-90 seg. Cerimónia final tipo Oscars. Vídeos ficam com a empresa.

**Família:** 🏢 Hive (com filmagem outdoor)
**Duração:** dia inteiro (5-6h) ou meio-dia intensivo (4h)
**Participantes:** 12–36 (equipas de 4-6)
**Local:** espaço com salas + zonas outdoor variadas (quinta com salão, edifício com jardim)
**Estação:** todo o ano (chuva → variação estúdio)
**Público-alvo:** marketing, criativos, tech, retalho — qualquer equipa que valorize output partilhável

**Novidade — não estava no catálogo original.** Referência PT: Impakto oferece versões. Diferenciação: Backpackers usa **editores móveis (iPad Pro + LumaFusion)** — resultado em 90 min de edição, não em semanas.

## Objectivo pedagógico
Criatividade sob restrição, planeamento colectivo, produção com deadline, storytelling. **Entregáveis muito partilháveis** (LinkedIn, comunicação interna, kick-offs).

## O que a equipa vive
Cada equipa recebe um brief criativo (5 opções à escolha): "curta sobre o valor X da empresa", "manifesto em 60s", "curta que responde a esta pergunta filosófica", etc. Têm 4h para: script, filmagem, edição. Cerimónia final: exibição de todos os vídeos + votação Oscars.

## Briefs típicos (banco)

- "Um curta 60-seg sobre o que a nossa empresa acredita"
- "Um manifesto anti-reunião"
- "Uma paródia de anúncio publicitário sobre a vossa cultura"
- "Um mini-documentário sobre a pessoa mais nova da vossa empresa"
- "Um vídeo sobre 'coisas que ninguém ensina no primeiro dia'"
- "Uma explicação criativa do que a empresa faz — para uma criança de 8 anos"

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| iPad Pro + LumaFusion (edição) | 1 por equipa | ✅ (aluguer ~40€/dia) |
| Tripé para smartphone | 1 por equipa | ✅ |
| Microfones lapela | 1 por equipa | ✅ |
| Refletores / iluminação portátil | Set | ✅ |
| Fatos / adereços cenográficos | Kit variado | ✅ |
| Projector + tela para exibição | 1 | ✅ |
| Prémios Oscars simbólicos (troféus) | 3-5 | Consumível |
| Cronómetro grande | 1 | ✅ |

**Custo material** ≈ 120€ + 40€/dia por iPad Pro (aluguer parceiro fotografia).

## Fluxo (dia inteiro)

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Contexto + Oscars vibe | 20 min | Cria clima festival | Aquece |
| Escolha de briefs | 15 min | Apresenta 8-10 briefs | Escolhe |
| Script (mesas) | 45 min | Ensina estrutura básica | Escreve storyboard |
| Almoço | 60 min | Convive | Descomprime |
| Filmagem (livre) | 90 min | Circula, tira fotos | Filma |
| Edição em iPad | 90 min | Ajuda com técnica | Edita |
| Cerimónia Oscars | 60 min | Anima como MC | Exibe + vota |
| Prémios + fecho | 20 min | Anuncia | Celebra |

## Facilitador — checklist
- [ ] iPads Pro com LumaFusion instalado + carregado
- [ ] Tripés + microfones testados
- [ ] Cenografia / adereços preparados
- [ ] Sala de exibição pronta (projector + som)
- [ ] Prémios "melhor curta", "melhor actor", "melhor conceito", "prémio do público"
- [ ] Backup: se equipa não consegue editar, ter template pré-estruturado
- [ ] Vídeos exportados em alta resolução para entrega

## Brief para o cliente
- **O que vive:** "Vão passar meio dia a produzir vídeo em equipa. Vão descobrir quem tem visão criativa, quem executa, quem argumenta na sala de edição. Vão sair com vídeos reais para partilhar."
- **O que traz:** disposição para experimentar, criatividade, ir para fora da zona
- **O que levam:** 4-6 vídeos originais (~60-90s cada) prontos para comunicação, cerimónia gravada, atmosfera Oscars

## Follow-up
- **Todos os vídeos** em alta resolução (com direitos para uso interno)
- Vídeo de compilação da cerimónia
- Fotos "making of" + Oscars
- Convite: publicar em canais internos, LinkedIn empresa

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Equipa não sabe usar iPad/LumaFusion | Template pré-estruturado + facilitador ajuda |
| Vídeo fica com má qualidade | Kit de iluminação + microfones lapela |
| Cerimónia arrasta-se | Cronómetro rigoroso: 90s por vídeo + 2 min discussão |
| Alguém "só quer ficar de fora" | Papéis flexíveis (director, actor, editor, story) |

## Adaptações

- **Small team (12):** 2 equipas de 6, cada uma faz 2 vídeos (1 breve + 1 mais longo)
- **Grande grupo (36):** 6 equipas, 6 vídeos, cerimónia mais teatral
- **Focado em produto:** vídeos sobre o produto/serviço da empresa (viraliza)
- **Fim de ano:** vídeo "highlights do ano da vossa equipa"
- **Onboarding:** cada nova pessoa faz vídeo "quem sou eu em 60s"

## Notas de custos
Preço-alvo: **~55-70€/pax**. Ticket alto mas entrega concreta = fácil justificar.

## Parcerias-alvo
- Estúdio de fotografia/vídeo Leiria (aluguer iPads + kit)
- Editor freelance (backup)
`,
  },
  {
    code: `hive-08-backpackers-roundtable`,
    name: `🪑 Backpackers Roundtable`,
    tagline: `**Novidade 2026.** Ex-*Journey Within*, reescrita. Uma mesa de 8-12 líderes seniores. 3 horas de conversa facilitada estruturada. Sem PowerPoint. Sem agenda gestão.`,
    family: "hive",
    durationLabel: `3-4h (manhã ou tarde) ou dia inteiro (versão retreat curto)`,
    paxMin: 6,
    paxMax: 12,
    pricePerPaxMin: 90,
    pricePerPaxMax: 130,
    priceTargetMin: 90,
    priceTargetMax: 130,
    targetAudience: `C-level, Board, Comité de gestão, Founders, Alto-potenciais`,
    sortOrder: 8,
    body: `# 🪑 Backpackers Roundtable
> **Novidade 2026.** Ex-*Journey Within*, reescrita. Uma mesa de 8-12 líderes seniores. 3 horas de conversa facilitada estruturada. Sem PowerPoint. Sem agenda gestão.

**Família:** 🏢 Hive (small-group premium)
**Duração:** 3-4h (manhã ou tarde) ou dia inteiro (versão retreat curto)
**Participantes:** 6–12 (rigoroso, mais dilui)
**Local:** sala especial (biblioteca, quinta, sala de arte), longe do escritório
**Estação:** todo o ano
**Público-alvo:** C-level, Board, Comité de gestão, Founders, Alto-potenciais

**Novidade — não estava no catálogo original.** Reescrita da antiga "Journey Within" (que era vaga). Aqui é actividade **premium small-group**, ticket muito alto.

## Objectivo pedagógico
Alinhamento estratégico, verdades não-ditas, decisões difíceis destravadas, coesão de topo. Diferente do Connect Circle (mais emocional) — aqui é **estratégico e decisional**.

## O que a equipa vive
Chegam a um espaço especial (não o escritório). Mesa redonda. Sem agenda projectada. Facilitador (senior, com credibilidade C-level) conduz **3-4 conversas encadeadas** que fazem emergir o não-dito. Cada conversa termina com **decisão ou compromisso escrito**.

## Estruturas de conversa (exemplos)

Adaptar ao contexto do cliente. Sequência típica:

1. **"O que está a arder mas ninguém está a apagar?"** (elicitar problemas silenciados)
2. **"Se pudéssemos parar 3 coisas amanhã, quais seriam?"** (elicitar coragem de simplificar)
3. **"O que é que só nós conseguimos ver e que os outros não veem?"** (afirmar visão diferenciadora)
4. **"O que decidimos hoje que faz este ano diferente?"** (fechar com compromisso)

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Mesa redonda (biblioteca, quinta) | 1 | Externo — aluguer espaço |
| Blocos moleskin personalizados | 1 por pax | Consumível (marca a experiência) |
| Câmara para gravar áudio (apenas facilitador) | 1 | ✅ |
| Objecto "condutor" (bússola madeira) | 1 | ✅ |
| Refeição / catering premium | Almoço/jantar | Externo |
| Cenografia (velas, tecidos, luz suave) | Set | ✅ |

**Custo material** ≈ 40€ + aluguer espaço + catering

## Fluxo (versão 4h + almoço)

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Chegada + café | 20 min | Recebe individualmente | Chega |
| Contexto + regras | 15 min | Estabelece regras (confidencialidade, ouvir) | Aceita |
| Conversa 1 (o não-dito) | 60 min | Facilita, segura silêncios | Fala verdade |
| Intervalo | 15 min | Serve chá | Descomprime |
| Conversa 2 (parar 3 coisas) | 45 min | Facilita | Concentra |
| Almoço | 60 min | Convive | Continua informalmente |
| Conversa 3 (visão) | 45 min | Facilita afirmação | Consolida |
| Conversa 4 (compromissos) | 30 min | Escrita ao vivo | Compromete-se |
| Fecho ritual | 15 min | Fecha simbolicamente | Sai transformada |

## Facilitador — checklist
- [ ] Facilitador com **experiência C-level real** (mínimo 10 anos gestão sénior + facilitação)
- [ ] Pré-entrevista individual com cada participante (30 min cada, 1 sem antes)
- [ ] Preparar mapa dos temas emergentes das pré-entrevistas
- [ ] Espaço reservado + catering premium
- [ ] Sem telemóveis (regra rígida)
- [ ] Sem projector, sem chat, sem MS Teams background
- [ ] Compromissos escritos à vista de todos no final

## Brief para o cliente
- **O que vive:** "Não é workshop. Não é reunião estratégica. É uma mesa onde vão dizer aquilo que normalmente ninguém diz, e sair com 2-3 decisões concretas. É pesado. É útil. É para quem está pronto."
- **O que traz:** verdade, disposição para se expor a pares, confidencialidade
- **O que levam:** compromissos escritos com owners + prazos, relatório-síntese (2 páginas, confidencial) do facilitador

## Follow-up
- **Relatório confidencial** (2 páginas) — temas emergentes, decisões tomadas, plano de execução
- Follow-up individual (1 chamada de 30 min por pessoa) 30 dias depois
- **Convite retorno 90 dias** (~50% dos clientes contratam) — rever compromissos

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Alguém "toma a mesa" | Facilitador redistribui via regra do objecto |
| Conflito latente irrompe | Facilitador reenquadra: "isto é ouro, mas continuemos" |
| Compromissos escritos não são cumpridos | Follow-up 30 dias é obrigatório |
| Cliente quer "resultado imediato" | Enquadrar: valor está no processo + follow-up |

## Adaptações

- **6-8 pax:** foco em Board / C-suite pequeno
- **12 pax:** foco em Comité gestão média
- **1 dia inteiro:** adicionar dinâmicas afternoon (case study, brainstorm estratégico)
- **Retreat 24h:** combinar com almoço + jantar + reflexão manhã seguinte
- **Off-site multi-dia:** combinar com Adventures + Roundtable (versão híbrida rara)

## Notas de custos
Preço-alvo: **~90-130€/pax**. **Ticket premium** justificado por: facilitador sénior, pré-entrevistas, espaço + catering, relatório confidencial, follow-up.

Este é o **produto mais alto ticket** do catálogo. Vender a Board / C-suite.
`,
  },
  {
    code: `multi-01-caminho-santiago`,
    name: `🌄 Caminho de Santiago (retreat 3-5 dias)`,
    tagline: `Retreat multi-dia num dos percursos mais históricos da Europa. A equipa caminha junta, dorme junta, celebra junta. É o **ticket mais alto e diferenciador** do catálogo.`,
    family: "multi",
    durationLabel: `3, 4 ou 5 dias`,
    paxMin: 4,
    paxMax: 20,
    pricePerPaxMin: null,
    pricePerPaxMax: null,
    priceTargetMin: 450,
    priceTargetMax: 600,
    targetAudience: `C-suite, equipas seniores, retreats anuais premium, celebrações de marco`,
    sortOrder: 1,
    body: `# 🌄 Caminho de Santiago (retreat 3-5 dias)
> Retreat multi-dia num dos percursos mais históricos da Europa. A equipa caminha junta, dorme junta, celebra junta. É o **ticket mais alto e diferenciador** do catálogo.

**Família:** 🌄 Multi-dia (Wild + Synergy híbrido)
**Duração:** 3, 4 ou 5 dias
**Participantes:** 4–20 (limite = logística de alojamento)
**Local:** Portugal → Galiza (Caminho Português) — variantes: Central, Litoral, Espiritual
**Estação:** ideal Abril-Junho / Setembro-Outubro (evitar Julho-Agosto por calor e multidão)
**Público-alvo:** C-suite, equipas seniores, retreats anuais premium, celebrações de marco

## Referência do formato
Modelo executado com **Grupo Metaseguros, Maio 2026** (3 dias, 6 pessoas — Padrón → Milladoiro → Santiago). Ver \`../cases/metaseguros-2026/\` para material real.

## Objectivo pedagógico
Coesão profunda (superação partilhada), reflexão estratégica ("vamos a caminhar 25 km — o que aparece?"), reset colectivo, marca-momento no ano da empresa.

## O que a equipa vive
Não é férias. É retreat estruturado. Cada dia tem:
- Caminhada (15-25 km, ritmo acessível)
- **Momento de reflexão facilitada** (2 x 30 min por dia) — perguntas estruturadas ao longo do caminho
- Refeição partilhada
- Momento de silêncio individual à noite

No fim: chegada simbólica à Praça do Obradoiro + Missa do Peregrino + jantar de celebração.

## Percursos possíveis

| Variante | Duração | Distância total | Dificuldade | Preço-alvo |
|---|---|---|---|---|
| **Padrón → Santiago** (Metaseguros 2026) | 3 dias | ~50 km | Baixa (etapas curtas) | 450-600€/pax |
| **Tui → Santiago** | 5 dias | ~120 km | Média | 700-950€/pax |
| **Vigo → Santiago** | 4 dias | ~90 km | Média | 550-750€/pax |
| **Caminho Português Litoral** (Porto → Vigo → Santiago) | 7 dias | ~250 km | Alta | 1200-1600€/pax |
| **Caminho Espiritual** (variante rápida) | 4 dias | ~80 km | Média-alta | 700-900€/pax |

## Estrutura de custos (variante 3 dias, base Padrón → Santiago)

| Item | Custo | Notas |
|---|---:|---|
| Alojamento (2 noites, quarto duplo/individual) | 60-100€/pax/noite | Padrón (Hotel Scala) + Milladoiro (B&B Hotel) |
| Refeições (5 refeições estruturadas) | 25-40€/pax/refeição | Alguns jantares em restaurante local |
| Transporte Lisboa → Padrón + regresso Santiago → Lisboa | 80-120€/pax | Ou coche partilhado + gasolina |
| Facilitação (2 facilitadores 3 dias) | 500-750€ total | Fundador + guia certificado |
| Seguros + material navegação + kit peregrino | 30-50€/pax | Credencial peregrino + gel + primeiros socorros |
| Fotografia profissional (opcional, 1-2 dias) | 400-600€ | Externo |
| Margem Backpackers | ~40-50% do custo | Ver \`custos.md\` |

**Preço-alvo final por pax:** 450-600€ (3 dias) → 900-1400€ (7 dias)

## Fluxo típico — dia por dia (versão 3 dias)

### Dia 1 — chegada + kickoff

- Manhã: viagem Lisboa → Padrón (6h)
- Almoço em Padrón (Cocido gallego)
- Tarde livre + reconhecimento local
- Jantar de kickoff — facilitação: "porque estamos aqui?"

### Dia 2 — Padrón → Milladoiro (~24 km)

- 07h30 pequeno-almoço
- 08h30 partida a pé, primeira etapa
- Paragens: Iria Flávia (histórica), Santuário de A Escravitude, cruzeiro Rúa de Francos
- Almoço a meio (piquenique)
- 17h chegada a Milladoiro
- Jantar + **momento reflexão facilitada:** "o que descobriu hoje sobre a nossa equipa?"

### Dia 3 — Milladoiro → Santiago (~10 km) + chegada

- 08h partida
- Chegada Praça do Obradoiro ~12h — **momento simbólico**
- 12h30 Missa do Peregrino (opcional)
- Almoço de celebração + entrega Compostela
- Tarde livre em Santiago
- Regresso Lisboa (fim do dia ou dia seguinte)

## Equipamento necessário

**A empresa fornece a cada pax:**
- Kit peregrino: bastão + credencial + gel para pés + poncho + kit primeiros socorros
- Mochila pequena (10-15L) se não tiver

**Da equipa Backpackers:**
- Guia de montanha certificado (se percurso >30 km/dia)
- Kit médico completo + comunicações + GPS backup
- Fotógrafo (opcional dia 2-3)

## Facilitador — checklist antes do dia
- [ ] Confirmar todos os alojamentos (2-3 sem antes)
- [ ] Comprar credenciais + carimbos
- [ ] Confirmar transporte de bagagens (se aplicável)
- [ ] Reconhecimento presencial do percurso (obrigatório se novo)
- [ ] Meteorologia + plano B para chuva forte
- [ ] Seguros específicos + INEM regional
- [ ] Kit médico + telefone satélite se percurso remoto
- [ ] Contactos emergência de todos os participantes
- [ ] Testar todos os cachés/hotéis
- [ ] Preparar 5-6 perguntas de reflexão por etapa

## Brief para o cliente (2 sem antes)
- **O que vive:** "3 dias. 6-25 km/dia. Vão caminhar juntos. Vão silenciar juntos. Vão chegar à Praça do Obradoiro juntos. Não vão esquecer isto."
- **O que traz:**
  - Botas de trekking (fazer 3-4 caminhadas de teste antes)
  - Roupa em camadas + poncho impermeável
  - Meias trekking (2 pares)
  - Kit higiene mínimo (mochila leve)
- **O que levam:**
  - Credencial de peregrino com todos os carimbos
  - Compostela (certificado oficial)
  - Kit foto profissional
  - Relatório de reflexão colectiva
  - Memória sensorial partilhada — dura anos

## Follow-up
- Álbum fotográfico premium (100+ fotos editadas)
- Vídeo 3-4 minutos "highlights" — muito bom para comunicação da empresa
- Relatório de temas emergentes (2-3 páginas)
- Certificados individuais
- **Convite para retorno anual** — muitas empresas fazem isto tradição

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Lesão de pés (bolhas, torções) | Kit prevenção + botas pré-testadas + pausas frequentes |
| Chuva forte | Ponchos + capacidade de encurtar etapas |
| Alguém não aguenta ritmo | Ter opção de "pular etapa" (transporte para próximo hotel) |
| Alojamento cancelado | Backup listado |
| Doença súbita | Kit médico completo + seguro forte + hospital mais próximo mapeado |
| Rota confusa | GPS + guia certificado + reconhecimento prévio |

## Adaptações

- **Small team (4-6):** intimidade máxima, quartos individuais possíveis
- **Empresa quer variante mais fácil:** 3 dias, etapas curtas
- **Retreat premium C-suite:** adicionar bebida especial no fim de etapa + hotel 4*
- **ESG (Impact + Caminho):** adicionar 1 dia de voluntariado em ONG local do Caminho

## Notas de custos
Preço-alvo: **~450-600€/pax (3 dias)** → **~1200-1600€/pax (7 dias)**. **Ticket mais alto do catálogo.**

Ver detalhe cálculo em \`../custos.md\`.

## Documentos operacionais
- \`../cases/metaseguros-2026/Caminho_Santiago_Plano_Final.docx\` — plano final entregue
- \`../cases/metaseguros-2026/Pontecesures - Teo - Santiago.docx\` — variante etapa
- \`../cases/metaseguros-2026/Backpackers_Caminho_Santiago_metaseguros_2026.docx\` — proposta original
`,
  },
  {
    code: `multi-02-backpackers-reboot`,
    name: `🌌 Backpackers Reboot`,
    tagline: `**Novidade 2026.** Retreat 24-48h "desintoxica digital" numa quinta rural. Sem WiFi. Sem escritório. Sem PowerPoint. Só a equipa, ritmo lento, e conversas que só aparecem quando o corpo abranda.`,
    family: "multi",
    durationLabel: `24h (1 noite) ou 48h (2 noites)`,
    paxMin: 6,
    paxMax: 20,
    pricePerPaxMin: null,
    pricePerPaxMax: null,
    priceTargetMin: 300,
    priceTargetMax: 450,
    targetAudience: `C-suite, gestores stressed, startups em burnout, empresas pós-crise`,
    sortOrder: 2,
    body: `# 🌌 Backpackers Reboot
> **Novidade 2026.** Retreat 24-48h "desintoxica digital" numa quinta rural. Sem WiFi. Sem escritório. Sem PowerPoint. Só a equipa, ritmo lento, e conversas que só aparecem quando o corpo abranda.

**Família:** 🌄 Multi-dia
**Duração:** 24h (1 noite) ou 48h (2 noites)
**Participantes:** 6–20 (mais que isto perde intimidade)
**Local:** quinta rural com espaços amplos (Fórnea, Alcobaça, Alentejo, Serra da Estrela)
**Estação:** ideal Setembro-Novembro / Fevereiro-Maio
**Público-alvo:** C-suite, gestores stressed, startups em burnout, empresas pós-crise

**Novidade — não estava no catálogo original.** Mercado quente pós-pandemia: procura por "desintoxica digital + coesão de equipa".

## Objectivo pedagógico
Reset colectivo, redescoberta de coesão em ambiente lento, alinhamento estratégico sem urgência, wellbeing profundo. **Diferente do Roundtable (mais estratégico)** — aqui a mudança acontece pelo tempo lento.

## O que a equipa vive
Chega à quinta 17h de sexta. Devolvem telemóveis à entrada (opcional, mas incentivado). Cada dia tem:
- Manhã: caminhada leve + reflexão (30-45 min)
- Almoço + descanso
- Tarde: 1 dinâmica estruturada (Connect Circle ou Canvas of Ideas ou Corporate Roleplay leve)
- Fim de tarde: tempo livre (livros, hamacas, piscina)
- Jantar em mesa comum
- Fogo + conversa livre à noite

Facilitador está presente mas invisível — o menos possível.

## Estrutura típica (48h)

| Sexta 17h | Sábado 08h | Sábado 12h | Sábado 15h | Sábado 19h | Domingo 08h | Domingo 12h | Domingo 15h |
|---|---|---|---|---|---|---|---|
| Chegada + jantar leve | Caminhada 90 min + reflexão | Almoço | Canvas of Ideas ou Roundtable | Jantar + fogo | Yoga suave / meditação | Almoço + partilha final | Regresso |

## Alojamento típico

Parcerias-alvo:
- **Fórnea:** Casa Marilena, Cerca de Barreiras
- **Alcobaça:** Quinta de S. Vicente, Casa Grande
- **Alentejo:** Herdade do Sobroso, Convento São Paulo
- **Serra da Estrela:** Casa das Penhas Douradas

## Estrutura de custos (24h base)

| Item | Custo | Notas |
|---|---:|---|
| Alojamento (1 noite quarto duplo/individual) | 80-120€/pax | Depende do parceiro |
| Refeições (3-4 refeições) | 25-40€/pax/refeição | Comida caseira local |
| Facilitação (2 dias fundador) | 500-750€ total | +/– facilitador auxiliar |
| Transporte grupo | 50-100€/pax | Coche colectivo |
| Material + kit peregrino digital detox | 30-50€/pax | Livro guia + caderno + kit |
| Actividades (yoga, guia natureza) | Externo se aplicável | Parceria |
| Fotografia profissional | 400-600€ | Opcional (2 momentos) |
| Margem Backpackers | ~40-50% custo | Ver \`custos.md\` |

**Preço-alvo final por pax:** 300-450€ (24h) → 500-750€ (48h)

## Fluxo — versão 24h (sexta 17h → sábado 17h)

### Sexta

- **17h** Chegada + check-in individual
- **18h** Kit boas-vindas — livro + caderno + explicação regras (telemóvel opcional)
- **19h** Círculo de abertura (Connect Circle 60 min)
- **20h30** Jantar em mesa comum
- **22h** Fogo + conversa livre / silêncio

### Sábado

- **07h30** Pequeno-almoço + mindfulness suave
- **09h** Caminhada 90 min + reflexão facilitada
- **11h** Livre / hamaca / livro
- **12h30** Almoço
- **14h** Dinâmica estruturada — 90 min (escolher: Canvas of Ideas OU Roundtable OU Corporate Roleplay leve)
- **16h** Círculo de encerramento
- **17h** Regresso

## Equipamento necessário

**A empresa fornece:**
- Caderno moleskin premium por pax
- Livro-guia "48h sem urgência" (curador da Backpackers)
- Kit peregrino digital detox (relógio caixa, chaveiro, etiqueta para telemóvel)

**Da Backpackers:**
- Facilitador
- Guia de natureza (para caminhada)
- Instrutor yoga/mindfulness (opcional, parceria)
- Kit médico + comunicações emergência

## Facilitador — checklist antes do dia
- [ ] Confirmar quinta 4 sem antes
- [ ] Kit boas-vindas preparado por pax
- [ ] Roteiro de dinâmicas ajustado ao perfil da equipa (call 1 sem antes)
- [ ] Meteorologia + plano B indoor
- [ ] Facilitador auxiliar / yoga instructor confirmado
- [ ] Ementa acordada com cozinha da quinta (dieta especial)
- [ ] Contactos emergência de todos
- [ ] Fotógrafo confirmado (2 momentos)

## Brief para o cliente (2 sem antes)
- **O que vive:** "Vão parar durante 24 (ou 48) horas. Vão descobrir que a vossa equipa consegue estar junta sem projectar, sem responder emails, sem urgência. Vão sair diferentes — mais alinhados, mais leves."
- **O que traz:** roupa confortável + camadas, calçado prático, livro pessoal, disposição para desacelerar
- **O que levam:** vídeo curto "moments" + fotos + insights escritos + compromissos individuais + memória sensorial

## Follow-up
- Álbum fotográfico
- Vídeo 90-s "the reset"
- Relatório de temas emergentes
- Convite para 90 dias depois — call de 30 min "estão a manter o ritmo?"
- **Convite retorno anual** — ~60% clientes voltam

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Alguém "vicia telemóvel" | Regra soft: caixa para telemóveis. Não obrigatório |
| Chuva | Quinta com espaços indoor amplos + adaptação livre |
| Alguém não gosta de "abrandar" | Ter opções (livros, hamaca, biblioteca) |
| Alguém adoece | Kit médico + hospital regional mapeado |
| Equipa quer "resultados objectivos" | Enquadrar antes: valor é subjectivo mas profundo |

## Adaptações

- **Small team (6-8):** intimidade máxima, quartos individuais possíveis
- **48h:** mais tempo para dinâmicas + segunda caminhada
- **C-suite premium:** adicionar chef privado + wine tasting + biblioteca curada
- **ESG:** combinar com Backpackers Impact numa causa local + 1 dia reset
- **Startups burnout:** enfoque em recuperação, menos actividade estruturada

## Notas de custos
Preço-alvo: **~300-450€/pax (24h)** → **~500-750€/pax (48h)**. Ticket alto justificado por retiro premium + facilitação personalizada.

## Parcerias-alvo
- Quintas eventos rural (Fórnea, Alcobaça, Alentejo, Estrela)
- Instrutor yoga/mindfulness certificado
- Fotógrafo profissional
- Chef local (opcional para C-suite)
`,
  },
  {
    code: `wild-01-treasure-hunters`,
    name: `🔍 Treasure Hunters`,
    tagline: `Uma caça ao tesouro em terreno real. A equipa lê o mapa, decide o rumo, resolve os enigmas e chega à recompensa.`,
    family: "wild",
    durationLabel: `meio-dia (3-4h de actividade)`,
    paxMin: 10,
    paxMax: 40,
    pricePerPaxMin: 35,
    pricePerPaxMax: 40,
    priceTargetMin: 35,
    priceTargetMax: 40,
    targetAudience: `equipa de vendas, comercial, operações — todos os níveis`,
    sortOrder: 1,
    body: `# 🔍 Treasure Hunters
> Uma caça ao tesouro em terreno real. A equipa lê o mapa, decide o rumo, resolve os enigmas e chega à recompensa.

**Família:** 🌿 Wild
**Duração:** meio-dia (3-4h de actividade)
**Participantes:** 10–40 (equipas de 5-6)
**Local:** trilhos + zona intermédia sem grande desnível (Fórnea, Monte Real, Mata Nacional de Leiria)
**Estação:** todo o ano (com adaptação para chuva)
**Público-alvo:** equipa de vendas, comercial, operações — todos os níveis

## Objectivo pedagógico
Trabalhar raciocínio lógico sob pressão, colaboração entre membros com skills diferentes, e liderança emergente (não hierárquica). O grupo tem de decidir rapidamente quem lê o mapa, quem interpreta o enigma, quem se lembra do detalhe visto ao KM 2.

## O que a equipa vive
Recebem uma mochila com mapa em papel, bússola, folha de enigmas e cartão de pontos. Ganham a equipa que **primeiro** encontra os 5 pontos ou **mais** encontrar em 3 horas. Cada ponto exige resolver um enigma para o próximo. No fim, todas as equipas convergem para o mesmo tesouro final (piquenique de encerramento).

## Equipamento necessário

| Categoria | Item | Quantidade | Reutilizável |
|---|---|---:|---|
| Navegação | Mapas impressos + bússola | 1 por equipa | ✅ |
| Enigmas | Cartões enigmas laminados | 5-8 por equipa | ✅ |
| Pontuação | Cartões picadores + punção | 1 por equipa | ✅ |
| Segurança | Kit primeiros socorros | 1 total | ✅ |
| Comunicação | Walkie-talkies (backup) | 1 por equipa + 1 facilitador | ✅ |
| Marcadores | Fita colorida nos pontos | 5-8 | Consumível |
| Recompensa | Tesouro final (caixa madeira + snacks temáticos) | 1 | Cenário |
| Merch (opcional) | Bandana/braçadeira por equipa | 5-6 por equipa | Consumível |

**Custo material total** ≈ 60€ (referência 20 pax). Ver \`custos.md\`.

## Fluxo (fase por fase)

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Chegada + brief | 20 min | Divide equipas, entrega mochilas, explica regras | Escuta + faz perguntas |
| Warm-up navegação | 15 min | Demonstra bússola, mostra 1 ponto exemplo | Testa material |
| Caça | 2h30-3h | Circula, tira fotos, resolve empates | Corre, decide, resolve |
| Convergência | 15 min | Chama todos ao ponto final | Chega, senta, respira |
| Debrief + tesouro | 30 min | Facilita reflexão + entrega prémios | Partilha, come, ri |

## Facilitador — checklist antes do dia
- [ ] Fazer reconhecimento do percurso (2 dias antes) e confirmar acessos
- [ ] Testar todos os enigmas com uma pessoa externa
- [ ] Verificar meteorologia + ter plano B indoor
- [ ] Confirmar seguros activos
- [ ] Levar snacks + água em cache no ponto final
- [ ] Kit de primeiros socorros no carro + 1 no bolso
- [ ] Contactos de emergência das empresas (RH + INEM regional)
- [ ] Telemóvel + power bank + walkie-talkies carregados

## Brief para o cliente (pré-sessão)
Dizer:
- **O que vive:** "Vão navegar em trilhos reais na Fórnea. Cada equipa vai ter de negociar internamente quem lidera, quem lê o mapa, quem resolve o enigma. Não há guia, não há caminho certo. Só há o mapa e a vossa cabeça."
- **O que traz:** roupa confortável, ténis com aderência, mochila pequena, água.
- **O que levam:** fotos profissionais, gravação de vídeo curto, e um relatório de insights de equipa entregue 48h depois.

## Follow-up (pós-sessão)
- Envio de 15-20 fotos editadas em 48h
- Relatório de 2-3 páginas com insights observados (padrões de liderança, comunicação, coesão)
- Convite para call de 30 min com RH para discutir o plano de 30 dias
- Email 30 dias depois: "Como está a equipa? Alguma dinâmica mudou?"

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Equipa perde-se | Walkie-talkies + checkpoint obrigatório a meio |
| Chuva forte | Plano B indoor (Escape Quest indoor variante) |
| Lesão / entorse | Kit primeiros socorros + seguro RC + INEM à mão |
| Equipa desmotiva | Facilitador tem 3 dicas discretas por equipa |
| Um grupo termina muito depressa | Enigma bónus de reserva |

## Adaptações

- **Pequenos grupos (8-12 pax):** 2 equipas de 4-6, percurso mais denso
- **Grandes grupos (30+):** 5-6 equipas, 2 facilitadores, checkpoints obrigatórios
- **Chuva forte:** variante indoor "Escape Quest" (usar edifício com plantas mapeadas)
- **Empresa remote-first:** versão digital com app tipo Actionbound (parceiro a validar)

## Notas de custos
Preço-alvo: **~35-40€/pax**. Ver detalhe em [\`../custos.md\`](../custos.md).
`,
  },
  {
    code: `wild-02-pathfinder-escape`,
    name: `🗺 Pathfinder Escape Quest`,
    tagline: `O escape room chegou à floresta. A equipa está "presa" num cenário — só sai se resolver todos os desafios em 90 minutos.`,
    family: "wild",
    durationLabel: `meio-dia (3h de actividade + debrief)`,
    paxMin: 8,
    paxMax: 24,
    pricePerPaxMin: 40,
    pricePerPaxMax: 45,
    priceTargetMin: 40,
    priceTargetMax: 45,
    targetAudience: `equipas de desenvolvimento de produto, gestão de projecto, liderança emergente`,
    sortOrder: 2,
    body: `# 🗺 Pathfinder Escape Quest
> O escape room chegou à floresta. A equipa está "presa" num cenário — só sai se resolver todos os desafios em 90 minutos.

**Família:** 🌿 Wild
**Duração:** meio-dia (3h de actividade + debrief)
**Participantes:** 8–24 (equipas de 4-6)
**Local:** clareira delimitada (Fórnea, Monte Real, Mata Nacional) — precisa de ~500m² isolados
**Estação:** todo o ano (com adaptação chuva)
**Público-alvo:** equipas de desenvolvimento de produto, gestão de projecto, liderança emergente

## Objectivo pedagógico
Liderança, planeamento sob restrição de tempo, resolução de problemas com informação incompleta. Diferente do Treasure Hunters — aqui o cenário é fechado e o tempo é o inimigo declarado.

## O que a equipa vive
Cada equipa recebe uma cena inicial ("estão perdidos após uma expedição — o guia desapareceu, e há indícios de que uma tempestade se aproxima"). Encontram 4-6 puzzles espalhados no cenário. Cada resolvido dá pista para o seguinte. O último desbloqueia o "resgate" (símbolo: bússola do guia perdido).

Os puzzles combinam:
- **Físicos** (cordas, nós, torre de equilíbrio)
- **Lógicos** (código numérico, sequência)
- **Cooperativos** (só resolvem se 4 pessoas fizerem algo simultâneo)

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Kit escape room outdoor (caixas com cadeados) | 4-6 por equipa | ✅ |
| Cadeados de combinação (numéricos + letras) | 6 por equipa | ✅ |
| Cordas + nós de referência | 3 por equipa | ✅ |
| Bússola simbólica final | 1 por equipa | ✅ |
| Cenografia (fita fluorescente, pistas visuais) | Set | Reutilizável parcial |
| Timer visível (grande, ao ar livre) | 1 | ✅ |
| Relógio + walkie-talkies | Set | ✅ |

**Custo material** ≈ 90€. Kit inicial custa ~500€, amortizado em ~10 eventos.

## Fluxo

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Brief cenográfico | 20 min | Conta história, mostra timer | Escuta, alinha equipa |
| Puzzle 1 (fácil, orientador) | 15 min | Guia se necessário | Aprende regras |
| Puzzles 2-5 | 60 min | Circula, tira fotos | Resolve, delega, comunica |
| Puzzle final cooperativo | 15 min | Cronometra visível | Coordena todos |
| Debrief liderança | 30 min | Facilita: quem liderou? como? | Reflecte |
| Snack + fotos | 15 min | Convive | Descomprime |

## Facilitador — checklist
- [ ] Testar TODOS os puzzles com equipa externa (bugs matam a experiência)
- [ ] Preparar 2-3 dicas escondidas para dar em caso de bloqueio prolongado
- [ ] Cronómetro sempre visível (aumenta tensão)
- [ ] Não interromper puzzle a não ser que equipa esteja há >15 min sem progresso
- [ ] Fotografar momentos de "click" (quando puzzle é resolvido)
- [ ] Ter kit de reset rápido caso equipa avance rápido demais

## Brief para o cliente
- **O que vive:** "Vão viver 90 minutos de tensão colaborativa. Vão descobrir quem lidera bem sob pressão, quem propõe soluções cedo, quem confirma antes de agir. Não há prémio individual — só a equipa toda 'sai' ou fica."
- **O que traz:** roupa outdoor confortável, calçado próprio para terreno irregular
- **O que levam:** vídeo curto editado, relatório de dinâmicas de liderança observadas, fotos

## Follow-up
- Envio de 10-15 fotos editadas em 48h
- **Relatório de liderança** (2 páginas) identificando padrões: quem propôs primeiro, quem consolidou consenso, quem executou. Muito útil para o RH em promoções/rotações.
- Call de 30 min opcional para discutir o mapa de liderança

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Puzzle bugado | Sempre testado + facilitador tem key master |
| Equipa fica frustrada | Dica silenciosa aos 15 min de bloqueio |
| Tempo esgota sem resolver | Extensão de 15 min + prémio de participação (evita ferir moral) |
| Chuva | Cenário alternativo em telheiro/pavilhão |

## Adaptações

- **Pequenos grupos (6-8):** 1 equipa, versão mais complexa (6 puzzles vs 4)
- **Grandes grupos (24+):** paralelismo de 4 equipas em 4 cenários diferentes
- **Startup tech:** puzzles com programação/código (parceria com dev freelance)

## Notas de custos
Preço-alvo: **~40-45€/pax**. Kit inicial 500€ amortizado em 8-10 eventos.
`,
  },
  {
    code: `wild-03-snapshot-challenge`,
    name: `📸 Snapshot Challenge`,
    tagline: `A equipa tem 2 horas e 8 briefs criativos. Cada equipa entrega 8 fotos que contam uma história.`,
    family: "wild",
    durationLabel: `meio-dia (2-3h + curadoria colectiva)`,
    paxMin: 8,
    paxMax: 40,
    pricePerPaxMin: 30,
    pricePerPaxMax: 35,
    priceTargetMin: 30,
    priceTargetMax: 35,
    targetAudience: `marketing, criativos, comercial, RH — quem quiser criatividade`,
    sortOrder: 3,
    body: `# 📸 Snapshot Challenge
> A equipa tem 2 horas e 8 briefs criativos. Cada equipa entrega 8 fotos que contam uma história.

**Família:** 🌿 Wild (mas indoor-adaptável)
**Duração:** meio-dia (2-3h + curadoria colectiva)
**Participantes:** 8–40 (equipas de 4-6)
**Local:** centro urbano ou natureza (Leiria centro, Fórnea, Monte Real)
**Estação:** todo o ano (chuva torna experiência mais interessante)
**Público-alvo:** marketing, criativos, comercial, RH — quem quiser criatividade

## Objectivo pedagógico
Criatividade sob restrição (brief fechado, tempo limitado), comunicação visual, decisões colectivas rápidas ("qual das 15 fotos submetemos?").

## O que a equipa vive
Recebem 8 briefs de fotografia — não literais, mais tipo:
- "Uma foto que mostre coragem"
- "Uma foto que soa a manhã de segunda"
- "Uma foto que a mãe do director gostaria"

Só usam smartphones. Voltam ao ponto de convergência ao fim de 2h com **as suas 8 melhores**. Curadoria colectiva final — cada equipa apresenta, votam em júri cego.

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Cartões brief (8 por equipa) | Set laminado | ✅ |
| Projector + tela para curadoria | 1 | ✅ (aluguer se não tens) |
| Cabo AirDrop / Google Photos partilhada | 1 conta | ✅ |
| Prémio "melhor foto" | 1 (garrafa vinho local) | Consumível |
| App/plataforma partilha (Google Photos ou Dropbox) | Conta | ✅ |

**Custo material total** ≈ 30€. **A actividade mais barata do catálogo.**

## Fluxo

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Brief + regras | 15 min | Explica critérios | Aceita briefs, forma sub-equipas |
| Fotografia livre | 2h | Deixa em paz | Corre, discute, tira, escolhe |
| Retorno + upload | 20 min | Recebe fotos | Sobe fotos ao Drive/Photos |
| Curadoria colectiva | 45 min | Projecta, facilita | Comenta, defende |
| Votação + prémio | 15 min | Anuncia júri | Vota, celebra |

## Facilitador — checklist
- [ ] Testar upload de fotos com 1 pessoa antes do evento
- [ ] Ter power banks para telemóveis (equipa muitas vezes descarrega)
- [ ] Projector + tela testados
- [ ] 3-4 briefs de reserva caso um seja demasiado difícil no cenário
- [ ] Preparar 1-2 "moments" para curadoria (foto marcante + pergunta ao autor)
- [ ] Sequência de vídeo montada em 24h com melhores momentos

## Brief para o cliente
- **O que vive:** "Vão andar 2h como turistas na vossa cidade — mas com cabeça de artista. A criatividade vai emergir da limitação e do tempo."
- **O que traz:** smartphone carregado, ténis confortáveis, uma vontade de brincar
- **O que levam:** apresentação das melhores fotos em vídeo montado, direitos das fotos para uso interno da empresa

## Follow-up
- Vídeo montado 90-segundos das melhores fotos + música (entrega 48h)
- Álbum online partilhado (todas as fotos)
- Emprestar 3-5 fotos para site/comunicação da empresa (com créditos)
- Post LinkedIn conjunto (Backpackers + empresa) — se autorização

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Chuva forte | Interior — usa museu/edifícios/café |
| Alguém sem smartphone | Ter 1-2 câmaras de reserva |
| Fotos má qualidade / má-fé | Julgamento cego + rebranding de critérios |
| Fotos com pessoas estranhas sem autorização | Brief inclui "só fotografar coisas ou pessoas da equipa" |

## Adaptações

- **Pequenos grupos (8-10):** 2 equipas, briefs mais exigentes
- **Grandes grupos (30+):** 6 equipas, mais votação, prémios por categoria
- **Distribuído / remoto:** equipas em cidades diferentes, tudo online — óptimo para equipa multi-country
- **Combinar com jantar:** curadoria durante jantar informal

## Notas de custos
Preço-alvo: **~30-35€/pax**. Actividade mais barata a produzir — bom entry-level para empresas céticas.
`,
  },
  {
    code: `wild-04-mission-green`,
    name: `♻️ Mission Green`,
    tagline: `Voluntariado outdoor com equipa. Meia manhã de limpeza + plantação numa zona ambiental + reflexão colectiva. Fica no CV da empresa. Fica na cabeça da equipa.`,
    family: "wild",
    durationLabel: `meio-dia (3-4h)`,
    paxMin: 15,
    paxMax: 60,
    pricePerPaxMin: null,
    pricePerPaxMax: null,
    priceTargetMin: 40,
    priceTargetMax: 50,
    targetAudience: `empresas em fase de comunicação ESG, seguros, imobiliário, retalho — quem quer história para o relatório de sustentabilidade`,
    sortOrder: 4,
    body: `# ♻️ Mission Green
> Voluntariado outdoor com equipa. Meia manhã de limpeza + plantação numa zona ambiental + reflexão colectiva. Fica no CV da empresa. Fica na cabeça da equipa.

**Família:** 🌿 Wild (ESG-driven)
**Duração:** meio-dia (3-4h)
**Participantes:** 15–60 (a partir de 30, dois facilitadores)
**Local:** zona ambiental parceira (Mata Nacional Leiria, Serra d'Aire, praia local)
**Estação:** ideal Setembro-Novembro (plantação) ou Março-Maio (limpeza pós-Inverno)
**Público-alvo:** empresas em fase de comunicação ESG, seguros, imobiliário, retalho — quem quer história para o relatório de sustentabilidade

## Objectivo pedagógico
Responsabilidade social + trabalho em equipa + ligação a algo maior que a empresa. Marca a equipa emocionalmente e cria história partilhada.

## O que a equipa vive
Chegam ao terreno (parceria com ONG ou câmara). Recebem kit de limpeza/plantação. Fazem-no juntos, em turnos rotativos (algumas equipas plantam enquanto outras limpam, roda). No fim, ponto de reflexão colectiva ("o que fizemos hoje? o que fica?") e certificado individual + placa na zona plantada com nome da empresa.

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Luvas trabalho (par por pax) | ~30 | Consumível |
| Sacos lixo grandes | 10-20 | Consumível |
| Ferramenta plantação (enxada, pá pequena) | 10 | ✅ |
| Árvores/plantas autóctones | 30-100 | Consumível |
| Placa comemorativa | 1 | Cenário |
| Certificados personalizados | 1 por pax | Consumível |
| Kit primeiros socorros | 1 | ✅ |
| Merch (opcional): t-shirts recicladas | Por pax | Consumível |

**Custo material** ≈ 80€ + doação da empresa (~200-500€ para plantas + causa)

## Fluxo

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Contexto + brief | 20 min | Explica porque este sítio | Escuta contexto |
| Divisão de tarefas | 10 min | Distribui equipas | Alinha internamente |
| Trabalho | 2h | Coordena rotações | Executa |
| Ponto reflexão | 20 min | Facilita conversa circular | Partilha |
| Certificação | 15 min | Entrega certificados | Fotografa-se |
| Snack/piquenique | 30 min | Convive | Descontrai |

## Facilitador — checklist
- [ ] Confirmar parceria com ONG/câmara 4 semanas antes
- [ ] Autorização escrita para trabalhar no terreno
- [ ] Reconhecer riscos (buracos, ninhos, encostas)
- [ ] Ter plano de emergência com INEM local
- [ ] Certificados prontos com nome de cada pessoa
- [ ] Placa comemorativa gravada antes
- [ ] Ter fotógrafo profissional (foto vale ouro para comunicação ESG do cliente)

## Brief para o cliente
- **O que vive:** "Vão levantar a mão suja durante meia manhã. Vão ver o resultado no fim. Não é um team building — é um contributo. É por isso que fica."
- **O que traz:** roupa velha, calçado outdoor, protector solar/chapéu
- **O que levam:** certificado individual, foto profissional da placa comemorativa da vossa empresa no terreno, direito de comunicar como projecto ESG

## Follow-up
- Vídeo "before/after" da zona (curto, 60s) — óptimo para comunicação
- Certificados individuais em PDF de alta resolução
- Foto profissional da placa comemorativa
- Reportagem escrita 2 páginas para relatório sustentabilidade da empresa
- Visita opcional aos 6 meses para ver o crescimento

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Chuva | Reschedule (não fazer plantação em terreno saturado) |
| Lesão pequena | Kit + luvas + supervisão |
| Zona não preparada | Reconhecimento 1 semana antes |
| Equipa céptica sobre "esforço em vez de diversão" | Facilitador enquadra bem no início ("hoje construímos algo") |

## Adaptações

- **Pequenos grupos (15):** foco em plantação intensiva (~30 árvores)
- **Grandes grupos (60+):** dividir em 3 frentes (plantação + limpeza + inventário biodiversidade)
- **Cidade em vez de natureza:** limpeza de praia ou hortas urbanas
- **Empresa quer valor de comunicação alto:** dobrar tempo com jornalista + comunicação PR incluída

## Parceiros a cultivar
- Cáritas Leiria
- ICNF (Instituto Conservação da Natureza)
- ADAI (Associação Defesa Ambiente Interior)
- Câmara Municipal Leiria (Espaço Ambiente)
- Turismo de Leiria (co-branding)

## Notas de custos
Preço-alvo: **~40-50€/pax + doação da empresa**. A doação é chave — a empresa quer sentir que está a contribuir, não a "pagar diversão".
`,
  },
  {
    code: `wild-05-mystery-scenario`,
    name: `🎭 Mystery Scenario`,
    tagline: `Um mistério guiado num cenário real — a trilha perdida, o expresso nocturno, o caso arquivado. A equipa é o detective.`,
    family: "wild",
    durationLabel: `meio-dia a dia inteiro (4-6h)`,
    paxMin: 10,
    paxMax: 30,
    pricePerPaxMin: 50,
    pricePerPaxMax: 55,
    priceTargetMin: 50,
    priceTargetMax: 55,
    targetAudience: `equipas comerciais, jurídicas, consultoria, C-level — qualquer equipa cujo trabalho é resolver problemas ambíguos`,
    sortOrder: 5,
    body: `# 🎭 Mystery Scenario
> Um mistério guiado num cenário real — a trilha perdida, o expresso nocturno, o caso arquivado. A equipa é o detective.

**Família:** 🌿 Wild (com variante Hive)
**Duração:** meio-dia a dia inteiro (4-6h)
**Participantes:** 10–30 (equipas de 5-6)
**Local:** trilha + zona urbana (Leiria) ou espaço fechado (variante Hive)
**Estação:** todo o ano
**Público-alvo:** equipas comerciais, jurídicas, consultoria, C-level — qualquer equipa cujo trabalho é resolver problemas ambíguos

## Objectivo pedagógico
Pensamento crítico com informação incompleta, questionamento de premissas, colaboração inter-departamental (cada pessoa vê pistas diferentes por skill).

## O que a equipa vive
Chegam a um cenário com uma história misteriosa em curso. Recebem dossier inicial: fotos, testemunhos, pistas contraditórias. Têm 3-4h para descobrir "o que aconteceu". No fim, cada equipa apresenta a sua teoria. Só uma equipa está correcta.

## Guiões prontos (3 cenários)

Em \`../scripts-misterio/\`:

1. **Mistério na Trilha Perdida (v1)** — grupo desaparecido em trilho de montanha nos anos 80, cenário para Fórnea/Monte Real
2. **Mistério na Trilha Perdida (v2)** — variação mais curta, adaptada a hora e meia
3. **Mistério no Expresso Nocturno** — assassinato num comboio, cenário indoor (versão Hive)

**Vantagem competitiva:** os guiões já existem em papel. Nenhum concorrente PT tem isto pronto. É diferenciador imediato.

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Dossier inicial (fotos, testemunhos, mapa) | 1 por equipa | ✅ (reimprimir) |
| Envelopes pistas (5-8) | Set por equipa | ✅ |
| Cenografia (fotos "antigas", relógios, mapas velhos) | Set | ✅ |
| Kit forensic (lupa, spray revelador UV, luvas) | Set por equipa | ✅ |
| Câmara Polaroid para "evidências" | 1 | ✅ |
| Prémio de detective | 1 | Consumível |

**Custo material** ≈ 100€ (kit reutilizável). Kit inicial de 3 mistérios completos: ~600€, amortizado em 6-8 eventos.

## Fluxo (versão dia inteiro)

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Contexto teatral | 30 min | Actua narrador | Escuta |
| Descoberta cenário | 45 min | Guia (fingindo ser inspector) | Explora, faz perguntas |
| Investigação livre | 2h30 | Circula, revela pistas por progresso | Investiga, hipóteses |
| Retorno + preparação | 20 min | Deixa em paz | Consolida teoria |
| Apresentações | 45 min | Cronometra 8 min por equipa | Apresenta com convicção |
| Revelação + prémios | 20 min | Revela verdade | Vibra ou lamenta |

## Facilitador — checklist
- [ ] Estudar guião completo (facilitador é actor durante 30 min)
- [ ] Preparar 3-4 pistas de "resgate" (para dar em segredo se equipa bloqueada)
- [ ] Testar timing com uma equipa externa
- [ ] Preparar prémio simbólico (chapéu de detective, distintivo)
- [ ] Ter câmara para fotografar equipas em modo "detective"
- [ ] Ensaiar bem o momento da revelação (deve ser dramático)

## Brief para o cliente
- **O que vive:** "Vão viver uma história — não é actividade. Cada pessoa vai ter uma peça do puzzle, sem saber. Só quem falar bem, ouvir bem, e desafiar hipóteses, chega à verdade."
- **O que traz:** roupa outdoor (se Wild) ou smart casual (se Hive), curiosidade
- **O que levam:** vídeo de reveal, fotos "detective mode", relatório de dinâmicas de investigação observadas

## Follow-up
- Vídeo 90-s do dia editado como trailer de série detective
- Fotos "cinemáticas" em 48h
- **Relatório de pensamento crítico** — 3 páginas identificando: quem propôs hipóteses cedo, quem questionou premissas, quem consolidou o "case final"
- Convite para call de discussão

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Equipa chega à verdade cedo demais | Facilitador esconde a última pista mais tempo |
| Equipa perde-se no cenário | Pistas 2 e 5 têm mapa a esclarecer |
| Alguém não gosta de "acting" | Nunca pedir para representar — só para investigar |
| Cenário muito complexo | Simplificar dossier para 6 documentos em vez de 12 |

## Adaptações

- **Meio-dia (3h):** usar Mistério Trilha Perdida v2 (versão curta)
- **Pequenos grupos (10):** 2 equipas de 5, apresentação de peer-review
- **C-level (12-16):** versão premium com actor profissional convidado + cenografia elevada
- **Distribuído:** versão online por Zoom com dossier PDF partilhado

## Notas de custos
Preço-alvo: **~50-55€/pax**. Custo de preparação maior compensado por reutilização dos guiões.
`,
  },
  {
    code: `wild-06-backpackers-trials`,
    name: `🏆 Backpackers Trials`,
    tagline: `Ex-*Taskmaster*. Série de 5-8 desafios curtos, criativos, com regras absurdas. O júri decide. Ganha quem faz mais rir e mais pontos.`,
    family: "wild",
    durationLabel: `meio-dia (3-4h)`,
    paxMin: 12,
    paxMax: 30,
    pricePerPaxMin: 50,
    pricePerPaxMax: 55,
    priceTargetMin: 50,
    priceTargetMax: 55,
    targetAudience: `equipas jovens, empresas com forte cultura interna, celebrações de aniversário`,
    sortOrder: 6,
    body: `# 🏆 Backpackers Trials
> Ex-*Taskmaster*. Série de 5-8 desafios curtos, criativos, com regras absurdas. O júri decide. Ganha quem faz mais rir e mais pontos.

**Família:** 🌿 Wild (com adaptação Hive)
**Duração:** meio-dia (3-4h)
**Participantes:** 12–30 (equipas de 4-6)
**Local:** outdoor com espaço variado (jardim quinta, praia, terreno urbano)
**Estação:** todo o ano
**Público-alvo:** equipas jovens, empresas com forte cultura interna, celebrações de aniversário

> **Nota copyright:** o nome "Taskmaster" é marca registada de Alex Horne / Avalon Entertainment no contexto de show televisivo. Uso em contexto team building é área cinzenta. **Renomeado para "Backpackers Trials"** por segurança e coerência de marca. O formato (desafios curtos + júri) não é protegido.

## Objectivo pedagógico
Criatividade sob restrições absurdas, resiliência humorística, comunicação rápida em equipa, capacidade de propor soluções não-óbvias. **Muito bom para libertar equipa tensa.**

## O que a equipa vive
Cada equipa recebe um "brief master" com 8 tarefas. Cada tarefa tem regra estranha ("faz aparecer o número 7 sem escrever", "leva 3 sapatos ao topo do escorrega"). Têm 30 min por tarefa. Facilitador é júri. Pontos por criatividade + execução + violação inteligente de regras.

Estilo baseado no show inglês *Taskmaster*, adaptado para PME PT.

## Exemplos de tarefas

- "Coloca o maior objecto redondo que encontrares dentro deste anel de 20cm" (limites de tempo + interpretação criativa)
- "Faz o presidente da vossa equipa parecer surpreendido com algo — mas sem que ele saiba que é a tarefa"
- "Constrói uma torre de 1 metro com 6 objectos, sem tocar em nenhum"
- "Faz aparecer o número 7 sem escrevê-lo em lado nenhum"
- "Traz-me o melhor sorriso que conseguires arrancar a um estranho"
- "Prepara em 15 min uma canção original sobre a vossa empresa"

## Equipamento necessário

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Envelopes tarefa (5-8 tarefas) | Set por equipa | ✅ |
| Materiais de reserva (cordas, cartão, marcadores, objectos vários) | Kit grande | ✅ |
| Câmara para capturar tarefas | 1 | ✅ |
| Placar de pontuação | 1 | ✅ |
| Prémio troféu "Master das Trilhas" | 1 | Reutilizável |
| Cronómetro grande visível | 1 | ✅ |

**Custo material** ≈ 120€ (inicial). Materiais reutilizáveis: kit inicial ~400€.

## Fluxo

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Brief tarefas + regras | 20 min | Estabelece autoridade "júri" | Recebe missão |
| Tarefas 1-4 | 90 min | Facilita + julga | Executa em rondas |
| Snack + reset | 15 min | Convive | Reagrupa |
| Tarefas 5-8 | 60 min | Facilita | Executa |
| Cerimónia final | 30 min | Reveal ranking + troféu | Vibra ou lamenta |
| Debrief opcional | 20 min | Facilita: o que aprenderam? | Reflecte |

## Facilitador — checklist
- [ ] Preparar 10-12 tarefas em envelopes (algumas de reserva)
- [ ] Ter autoridade + sentido de humor no acto de julgar
- [ ] Câmara/telemóvel para gravar momentos-chave
- [ ] Placar de pontuação visível
- [ ] Ter troféu preparado
- [ ] Não tomar tudo a sério — o humor é 60% do valor

## Brief para o cliente
- **O que vive:** "Vão passar meia manhã a ser criativos com regras absurdas. Vão descobrir quem, na equipa, tem cabeça lateral, quem quebra regras com inteligência, e quem faz rir. O ambiente vai ficar completamente diferente do escritório."
- **O que traz:** roupa outdoor confortável, disposição para se rir de si próprio
- **O que levam:** vídeo hilariante 90-s do dia, fotos das tarefas, troféu virtual "Best Team" para o mural do escritório

## Follow-up
- Vídeo montado 90-s com os melhores momentos (viral potencial interno)
- Foto "hall of fame" — melhor tarefa executada
- Certificado "Backpackers Trials Champion" para equipa vencedora

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Tarefa demasiado difícil | Ter versão "easy mode" de reserva |
| Equipa não entra no espírito | Facilitador puxa energia com humor + gamification |
| Alguém magoa-se em tarefa física | Nunca tarefas com risco físico real; escolher activo mas seguro |
| Chuva | Versão indoor com tarefas indoor-friendly (kit alternativo) |

## Adaptações

- **Pequenos grupos (12):** 2 equipas competindo, mais tempo por tarefa
- **Grandes grupos (30):** 5-6 equipas, mais tarefas paralelas, precisa 2 facilitadores
- **Empresa hierárquica:** incluir tarefa "cada equipa deve fazer X com o CEO fora do papel de CEO"
- **Combinar com jantar:** cerimónia final durante jantar informal

## Notas de custos
Preço-alvo: **~50-55€/pax**. Ver \`custos.md\`.

## Caso de referência
**Imóveis+, Julho 2024** — 22 pax em 4 equipas de 5-6. Formato meio-dia. Feedback positivo do RH. Foi este evento que criou a relação.
`,
  },
  {
    code: `wild-07-backpackers-impact`,
    name: `💚 Backpackers Impact`,
    tagline: `Meia manhã de voluntariado real com ONG local. A equipa larga o crachá e faz algo que fica no bairro.`,
    family: "wild",
    durationLabel: `meio-dia (3-4h)`,
    paxMin: 10,
    paxMax: 50,
    pricePerPaxMin: 35,
    pricePerPaxMax: 40,
    priceTargetMin: 35,
    priceTargetMax: 40,
    targetAudience: `empresas com forte comunicação de propósito, retalho, seguros, ESG-driven`,
    sortOrder: 7,
    body: `# 💚 Backpackers Impact
> Meia manhã de voluntariado real com ONG local. A equipa larga o crachá e faz algo que fica no bairro.

**Família:** 🌿 Wild (ESG)
**Duração:** meio-dia (3-4h)
**Participantes:** 10–50 (a partir de 25, dois facilitadores)
**Local:** parceiro social local (ONG, escola, lar, banco alimentar)
**Estação:** todo o ano
**Público-alvo:** empresas com forte comunicação de propósito, retalho, seguros, ESG-driven

**Novidade 2026 — não estava no catálogo original.** Diferente de Mission Green (natureza): aqui é ajuda social directa.

## Objectivo pedagógico
Empatia + coesão + sentido de propósito. Extremamente valioso para empresas que estão a "reconstruir cultura pós-COVID".

## O que a equipa vive
Não vão a um passeio de solidariedade. Vão trabalhar numa causa concreta com pessoas concretas. Pode ser:
- Recuperar espaço de uma associação (pintar, reparar)
- Servir refeições num centro social
- Organizar armazém de banco alimentar
- Dar formação numa escola (usando skills profissionais da equipa)
- Acompanhar visita cultural a lar de idosos

## Equipamento necessário

Depende do parceiro. Genérico:

| Item | Quantidade | Reutilizável |
|---|---:|---|
| Luvas + máscaras + delantais | 1 por pax | Consumível |
| Ferramenta específica (pincéis, panelas, arrumação) | Kit conforme causa | Reutilizável parcial |
| Certificados de voluntariado | 1 por pax | Consumível |
| Merch simbólico (t-shirt "Backpackers Impact 2026") | 1 por pax | Consumível |

**Custo material** ≈ 40€ + doação da empresa (empresa paga ~500-2000€ à ONG)

## Fluxo

| Fase | Tempo | Facilitador | Equipa |
|---|---|---|---|
| Recepção pelo parceiro social | 20 min | Facilita apresentações | Escuta a história do parceiro |
| Contextualização | 20 min | Assegura que ninguém está "só para foto" | Compreende impacto |
| Trabalho concreto | 2h | Coordena tarefas | Executa em equipa |
| Momento partilha | 30 min | Facilita conversa com beneficiários | Ouve histórias |
| Certificados + agradecimento | 15 min | Fecho formal | Recebe |
| Debrief interno curto | 15 min | Facilita: "o que levas?" | Reflecte |

## Facilitador — checklist
- [ ] Confirmar parceiro social 6 semanas antes (não improvisar)
- [ ] Visita prévia ao terreno (2 semanas antes)
- [ ] Alinhar expectativas — trabalho REAL, não teatro
- [ ] Preparar contexto histórico do parceiro social (a equipa deve saber com quem trabalha)
- [ ] Ter fotógrafo profissional (foto = comunicação ESG)
- [ ] Certificado individual pronto
- [ ] Convite ao parceiro para falar 5 min sobre a causa

## Brief para o cliente
- **O que vive:** "Vão sair do escritório e trabalhar meia manhã por outra pessoa. Não é passeio, não é entretenimento. É trabalho real. É por isso que muda."
- **O que traz:** roupa velha, calçado prático, disposição para se sujar
- **O que levam:** certificado + foto + reportagem para comunicação ESG + relação a longo prazo com um parceiro social

## Follow-up
- Reportagem (2 pág) sobre o dia + impacto quantificado
- 20-30 fotos profissionais editadas
- Vídeo 60-s "impact story"
- Certificados individuais em PDF alta resolução
- **Programa anual sugerido** — a empresa mantém 4 dias/ano de Impact com o mesmo parceiro (upsell recorrente)

## Riscos & mitigação

| Risco | Mitigação |
|---|---|
| Parceiro social não preparado | Visita prévia + briefing conjunto |
| Equipa "só quer selfie" | Facilitador enquadra logo no início |
| Trabalho não é dignificante | Curadoria de causas + evitar "chuva de generosidade" superficial |
| Empresa quer só "acto de RP" | Recusar contrato se claro que não é honesto |

## Parceiros a cultivar

| Tipo | Parceiro alvo | Nota |
|---|---|---|
| Banco alimentar | Banco Alimentar contra a Fome Leiria | Voluntariado logístico frequente |
| Educação | Escola EB1 rural, projecto ler+ | Formação usando skills da empresa |
| Sénior | Lar Nª Sra Fátima, Santa Casa Leiria | Acompanhamento, actividades culturais |
| Ambiental | Cáritas Leiria + terrenos degradados | Mistura com Mission Green |
| Refugiados | JRS Portugal (delegação Centro) | Tema global de forte comunicação |

## Adaptações

- **Pequenos grupos (10):** foco em causa mais íntima (lar, escola)
- **Grandes grupos (50):** dividir em 3-4 causas paralelas, retorno colectivo
- **Empresa quer "medir impacto"** — parceria com métricas quantificadas (kg de alimento, m² pintados, nº de pessoas apoiadas)
- **Empresa distribuída:** 3 cidades PT em simultâneo com 3 parceiros locais

## Notas de custos
Preço-alvo: **~35-40€/pax**. A empresa cobre a doação separadamente (fiscalmente vantajoso para ela).
`,
  },
];
